<?php

namespace DB\Bundle\dbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
	public function findUser($user) {
		$qb = $this->createQueryBuilder('a');
		$qb ->where('a.user = :user') ->setParameter('user', $user)
			->orderBy('a.createDate', 'DESC');
		return $qb->getQuery()->getResult();
	}
}
