<?php

namespace DB\Bundle\dbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaRepository extends EntityRepository
{
	public function findByAlbums($user, $album) {
		$qb = $this->createQueryBuilder('m');
		$qb ->where('m.user = :user') ->setParameter('user', $user)
			->andwhere('m.album = :album') ->setParameter('album', $album)
			->orderBy('m.createDate', 'DESC');
		return $qb->getQuery()->getResult();
	}
}
