<?php

namespace DB\Bundle\dbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MultimediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MultimediaRepository extends EntityRepository
{
}
