<?php

namespace DB\Bundle\dbBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function findByNameOrSurname($name) {
		$qb = $this->createQueryBuilder('u');
		$qb->where('u.name like :name') ->setParameter('name', '%'.$name.'%')
			->orWhere('u.surname like :name') ->setParameter('name', '%'.$name.'%')
			->orWhere('u.username like :name') ->setParameter('name', '%'.$name.'%')
			->orWhere('u.job like :name') ->setParameter('name', '%'.$name.'%')
			->orderBy('u.username', 'ASC'); 
		return $qb->getQuery()->getResult();
	}
}
